### ISSUE TITLE
make the promoter print out a JSON dump (summary) of everything that happened

### ISSUE THREAD

**Issue by listx** [kubernetes-sigs/k8s-container-image-promoter#117]
This paves the way for other tooling to integrate with the promoter, and also simplifies what to look at when we parse the logs as humans after a promotion run (in Prow).

The logs are cumbersome to parse by human eyes, so at least printing out a (prettified) JSON at the very end of a promotion run could make it easier to see what went OK and what went wrong.

**Comment by listx** [comment]
/remove-lifecycle stale

I think this issue will really help increase the readability of the logs, which are currently pretty verbose.

**Comment by yodahekinsew** [comment]
I can take a look at this issue
