### ISSUE TITLE
feature request: promote to multiple destination repos (aka "mirroring")

### ISSUE THREAD

**Issue by listx** [kubernetes-sigs/k8s-container-image-promoter#13]
This way, we can simulate a "mirroring" operation. That is, copy to multiple destination registries instead of just 1.

For the manifest, instead of just accepting a YAML string for `registries: dest: ...`, it could accept an array of strings. And then we would run the copy (promotion) operations in parallel for each destination registry.

**Comment by listx** [comment]
I'm wondering if we should make each `dest` registry also have a service account field. That way we don't have to use the same service account across all `dest` registries.

The more I think about this, the more it makes sense. The downside is that we have to import multiple secrets into Prow to plumb it all together, but I think it's worth the security advantages (let's try to give each service account as *few* privileges as possible --- aka [Principle of Least Privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege)).

**Comment by javier-b-perez** [comment]
Unless you will run the promoter in a different environment per `dest` registry, I don't see the point of using multiples service accounts. At the end the 'main' job will have access to all the SAs.

**Comment by listx** [comment]
So, given multiple `dest` registries, are you saying we should make them all readable/writable by 1 global service account, in order to be used by a single promoter process (invocation)? I don't like that because it unnecessarily makes the promoter less flexible.

Allowing each `dest` registry to specify its own service account doesn't mean that they will have to be different in practice. They could be the same in some situations, and different in other situations.
