### ISSUE TITLE
add support for promoting V2 Schema 1 (2.1) images

### ISSUE THREAD

**Issue by listx** [kubernetes-sigs/k8s-container-image-promoter#130]
This is because the way in which we use the new go-containerregistry library for doing the image copies only supports Version 2 Schema 2 images.

There are several choices:

1. wait for go-containerregistry to expose its `copySchema1Image` function that `gcrane` internally uses
2. shell out to `gcrane` (which is the frontend CLI for go-containerregistry)
3. vendor all Go dependencies (including go-containerregiistry) and manually lift/import the code in `copySchema1Image` which references a private function called `legacy.CopySchema1`

I would strongly prefer the first option.

**Comment by jonjohnsonjr** [comment]
Use https://godoc.org/github.com/google/go-containerregistry/pkg/crane#Copy
