### ISSUE TITLE
make the -garbage-collect flag optionally promote to a trash repo

### ISSUE THREAD

**Issue by listx** [kubernetes-sigs/k8s-container-image-promoter#14]
Instead of simply deleting images outright for garbage collection (deletion of unreferenced images), we could also (in addition) promote the images to a trash repo. This way, we can feel a lot safer about deleting images. Another benefit is that we could priodically delete *all* images in the trash registry, if they are older than X days (super simple script --- just list all images by timestamps and then delete if older than X day --- this script could be run periodically by Prow).

The manifest YAML would need to have an extra field for describing the trash registry, probably like this:

```
registries:
  src: ...
  dest: ...
  trash: ... <--- new field
```

This would play out as follows:
- image `foo:1.0` gets added into the promoter manifest
- promoter runs, and it gets added into the `dest` registry (or registries, as per #13)
- (some time passes, and `foo:1.0` becomes deprecated)
- image `foo:1.0` is removed from the manifest
- promoter runs, and now treats all instances of `foo:1.0` as an extra tag to be deleted --- with the `-delete-extra-tags` flag on, it deletes them from all `dest` registries
- NEW: at this point, the promoter *also* promotes `foo:1.0` into the new `trash` registry

**Comment by cpanato** [comment]
I'm on it.
I bit busy this week but next will finish

**Comment by amy** [comment]
@cpanato Hello! Is this still something you're working on / merged?

**Comment by listx** [comment]
Looking at this again, I don't think it's a good first issue. Mainly because of the complications around renames (imagine an image that gets renamed during promotion gets deleted --- what happens now?). Maybe it's something simple but I can't think of the obvious solution here.

**Comment by listx** [comment]
Sorry to double-post, but this issue is related to the larger topic of Disaster Recovery, which is the real beast we want to handle.

**Comment by cpanato** [comment]
@listx having troubles to understand where I need to add the new code, would say I agree this is not for the first issue :(
releasing this issue from my side to other can work on :/

**Comment by listx** [comment]
> @listx having troubles to understand where I need to add the new code, would say I agree this is not for the first issue :(
> releasing this issue from my side to other can work on :/

Yes, sorry about mis-labeling it earlier as a good first issue. If you have any questions on the other open issues, please feel free to "@" mention me. Thanks!

**Comment by listx** [comment]
Closing this as garbage collection is no longer in our radar.
