### ISSUE TITLE
add a -create-manifest flag

### ISSUE THREAD

**Issue by listx** [kubernetes-sigs/k8s-container-image-promoter#15]
If we want to use the promoter against a prod registry that already has a bunch of images, we have to manually insert each image into the manifest. This would be extremely time consuming. So, we should add a `-create-manifest` flag that populates a manifest's `images: ..` key with all the images found at a `dest` registry (if there are multiple, then maybe the union of all of them).

We already have the functions that fetch all images and digests+tags from an entire GCR registry, so this 
 feature would just unmarshal that data and then print it out as YAML to a file. The other fields like `registries: src: ...` would be filled with dummy data, to be filled out manually by a human.

**Comment by bartsmykla** [comment]
I could do that! :-)

**Comment by amy** [comment]
@bartsmykla Is this something you're still working on?

**Comment by amy** [comment]
Can be closed due to: https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/35

**Comment by listx** [comment]
Indeed, thanks @amy!
