### ISSUE TITLE
ParseThinManifestFromFile: limit path traversal

### ISSUE THREAD

**Issue by listx** [kubernetes-sigs/k8s-container-image-promoter#151]
Make the traversal path (1) relative-only and (2) limit its scope to only be within the `-thin-manifest-dir` directory.

**Comment by bartsmykla** [comment]
@listx I'm not sure if `ParseManifestFromFile` also should be limited, so I'll create PR with limiting both of them (it sounds to me as more reasonable), but if this one shouldn't be limited I'll change the PR.

**Comment by listx** [comment]
Closing this in favor of https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/161, which is more comprehensive (and stricter!). Please take a look @bartsmykla
