### ISSUE TITLE
Do not make -delete-extra-tags imply -garbage-collect

### ISSUE THREAD

**Issue by listx** [kubernetes-sigs/k8s-container-image-promoter#16]
This is because we want to separate promoter runs from garbage collection runs.

Separation of concerns ftw!

**Comment by hpandeycodeit** [comment]
@listx I am interested in this one. Any pointers to start with ?

**Comment by listx** [comment]
Hi @hpandeycodeit !

I think it's as simple as removing the if-block at https://github.com/GoogleCloudPlatform/k8s-container-image-promoter/blob/master/cip.go#L57 and also updating any related help text in that file.
