### ISSUE TITLE
add windows support

### ISSUE THREAD

**Issue by listx** [kubernetes-sigs/k8s-container-image-promoter#18]
Make sure that the promoter works from a windows machine. In theory golang is cross-platform (so is our dependency, `gcloud`), but it has not actually been tested.

**Comment by listx** [comment]
@thockin IIRC [this](https://github.com/kubernetes/kubernetes/issues/74134#issuecomment-465094512) was the reason for creating this issue. Did I misread that link (we need to test the promoter on Windows images, *not* that we need to compile the promoter to run as a Windows (.exe) binary)?

**Comment by javier-b-perez** [comment]
But the promoter will run in Prow. How is this related? 
We don't want humans to use the promoter, the promoter runs "as-a-service", right?

**Comment by listx** [comment]
Having had another look at the linked discussion, I believe we just need to make sure that the promoter understands windows images.

We use gcloud internally so this may already be supported. Someone needs to try to promote a windows image to verify it.

> But the promoter will run in Prow. How is this related?
> We don't want humans to use the promoter, the promoter runs "as-a-service", right?

Correct, the official promoter Prow jobs will *always* run as-a-service (unless there are emergencies or some such, but that should be the exception and not the rule).

**Comment by listx** [comment]
I've verified this experimentally. We actually never touch images ourselves (we have GCR promote it to another GCR), so it was already supported.

/close
