### ISSUE TITLE
cip-auditor: add slack integration

### ISSUE THREAD

**Issue by listx** [kubernetes-sigs/k8s-container-image-promoter#186]
By default the Stackdriver Error Reporting service sends an email. For high-volume inbox owners, this is probably just not good enough (might also get filtered out by email filters). Better to publish the errors on Slack so that everyone knows. We could publish to the #wg-k8s-infra channel to start with.

**Comment by dims** [comment]
oof! let's please create a separate channel unless this is a very very low volume of notification

**Comment by bartsmykla** [comment]
Agree with @dims but also agree it's good to publish the errors to slack

**Comment by listx** [comment]
I retitled this issue to lower the difficulty bar a bit, but I should just create a new issue instead of hijacking this one. Sorry about the noise!

**Comment by listx** [comment]
This has actually been done already by @thockin and others. For proof, see #k8s-infra-alerts.
