### ISSUE TITLE
support 'foreign' layers in manifest lists

### ISSUE THREAD

**Issue by listx** [kubernetes-sigs/k8s-container-image-promoter#19]
https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md#manifest-list

Currently this boils down to whether `gcloud` supports foreign layers because we have chosen to delegate all Docker manipulations to that tool. And because `gcloud` only works on GCR, it's a question of whether GCR supports foreign layers.

At the very least we can create an image with a foreign layer and try to test it being promoted in an e2e integration test.

**Comment by jonjohnsonjr** [comment]
Manifest lists generally don't have foreign layers, but manifests do.

As of https://github.com/google/go-containerregistry/pull/506 this should just work.

Can this be closed?

**Comment by listx** [comment]
As we rely more on go-containerregistry, I will defer to the upstream fix and call this closed.
