### ISSUE TITLE
allow remapping paths during promotion (do not force src registry to share same namespace as dest registry)

### ISSUE THREAD

**Issue by listx** [kubernetes-sigs/k8s-container-image-promoter#20]
Currently we expect the source image to have the *exact* same path as the destination path. This limits flexibility. We want to be able to optionally specify the target path in the destination, to allow it to be different than the source path.

This will require a slight tweak to the promoter manifest YAML.

**Comment by listx** [comment]
I'm thinking of adding a new field in the promoter manifest called `renames`, which will be a list of "links". E.g.:

```
renames:
- "gcr.io/foo/bar:gcr.io/some/path/banana" # colon is the separator between different names of the same image
```

The point is to make sure that all promotions of `bar` from `gcr.io/foo` to be named as `gcr.io/some/path/banana` (assuming that `gcr.io/foo` is the source registry). The rename entries could be arbitrarily long, like `a:b:c:d:...:x` --- the main requirement is that the renames paths must contain the source registry's naming scheme.

We perform set difference logic in order to figure out what images need to get promoted, what images are lost, etc. We would have to normalize the different names to share the same image name in order to make the set difference logic work. And then just before we promote images, we would have to use the (new) names stated in the `renames` field so that we name images correctly in the destination registries.

In graph-theory-speak, if images are nodes, then the `renames` field is a list of edges.

I can't think of a simpler way of doing this as far as the promoter manifest YAML structure is concerned; I thought of maybe adding rename information into each item under the `images` field directly, but it looked rather clumsy.

Thoughts @bartsmykla @thockin @javier-b-perez ?

**Comment by javier-b-perez** [comment]
what about this as an optional field?

```
images:
- name: apple
  dmap:
    "sha256:e8ca4f9ff069d6a35f444832097e6650f6594b3ec0de129109d53a1b760884e9": ["1.1", "latest"]
  rename: path/banana
```

The result will be
gcr.io/some/path/banana:1.1 same digest as src/apple:1.1

**Comment by listx** [comment]
> what about this as an optional field?
> 
> ```
> images:
> - name: apple
>   dmap:
>     "sha256:e8ca4f9ff069d6a35f444832097e6650f6594b3ec0de129109d53a1b760884e9": ["1.1", "latest"]
>   rename: path/banana
> ```
> The result will be
> gcr.io/some/path/banana:1.1 same digest as src/apple:1.1

There are a few reasons why I rejected this approach:
- I don't like how the rename value lives on its own, separate from the registry name and image name. It takes a little bit of mental calculation to do create `gcr.io/some/path/banana` in our heads. Having the full path like in my original post follows the "explicit is better than implicit" motto, which I think is important for these manifests that will be human-edited.
- The `a:b:c` approach allows for an image to be renamed differently for different registries (from `a` to `b` and `c`). It's more flexible, for free.
- Keeping all the renames on its own top-level field makes it very clear what images will be renamed for the whole file.

Also, instead of `a:b:c` we could have `[a, b, c]` (instead of a list of strings, a list of lists). It would make the parsing simpler.

**Comment by listx** [comment]
It's worth mentioning here that renames won't work until we tweak the "read the state of the world" logic we currently have; this is because the underlying `gcloud` command we use to read the GCR doesn't give us a full list of all images --- it only lists images at the root (and won't list images that are embedded under subdirectories). We need to read those images in nested subdirs because we will rename images as such as part of this feature. I realized this while making [this comment](https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/35#issuecomment-481941971).

I know what to do here, but this feature will take some effort to implement. @bartsmykla Unfortunately work on this feature will affect the --create-manifest feature you are working on. I suggest pausing that effort for now while this feature is ironed out.
