### ISSUE TITLE
add "--timeout" option to pull-cip-lint job 

### ISSUE THREAD

**Issue by yodahekinsew** [kubernetes-sigs/k8s-container-image-promoter#225]
The pull-cip-lint job will randomly fail on some pull requests due to timeout. Issue should be fixed by simply adding the "--timeout" option to the job with an arbitrary amount of time (something like 2 seconds).

**Comment by listx** [comment]
We invoke the pull-cip-lint job here: https://github.com/kubernetes/test-infra/blob/157a58118f01633f69d1623a09a49fb39f771d79/config/jobs/kubernetes/sig-release/cip/container-image-promoter.yaml#L122 with just "make lint-ci". Can you add the flag to our Makefile?

**Comment by yodahekinsew** [comment]
fixed with pull request #229
