### ISSUE TITLE
drain WaitGroup in ExecRequests after processing the request 

### ISSUE THREAD

**Issue by yodahekinsew** [kubernetes-sigs/k8s-container-image-promoter#237]
Currently, ExecRequests is meant to return an error if any of the requests it processes return an error. However, there is a bug where ExecRequests returns too early. ExecRequests returns after a WaitGroup has been drained (set to 0), but the WaitGroup is currently being drained before each request is fully finished being processed. This means that sometimes ExecRequests returns before finishing all requests. 

The error can simply be fixed by draining the WaitGroup whenever a request is fully finished being processed.

**Comment by listx** [comment]
Fixed in #238.
/close
