### ISSUE TITLE
add a vulnerability dashboard that surfaces all production image vulnerabilities

### ISSUE THREAD

**Issue by yodahekinsew** [kubernetes-sigs/k8s-container-image-promoter#253]
Continuing on the vulnerability check that was made, a vulnerability dashboard should be created that will surface all the image vulnerabilities for images that have been promoted. The vulnerability check is a good way of instantly surfacing vulnerabilities to users at the instant they promote an image, but it would be useful to have a platform that continuously surfaces these issues long after the promotion has finished.

A simple design for achieving this dashboard using a static page and GCS:
- [x] Setup a GCS bucket to host the vulnerability dashboard static html page
- [x] Setup a service account that has access to both Container Analysis Service information for production images and write access to the GCS bucket
- [x] Implement an adapter that can convert the vulnerability occurrence information stored in the Container Analysis Service into a parseable JSON
- [x] Upload an html page, json file containing vulnerability data, and js file that translates the json data into an html table to GCS
- [ ] Create a Prow job, that will run the adapter moving CAS information to the GCS json at the start of each day to update the static HTML page

**Comment by listx** [comment]
Thanks for tracking this @yodahekinsew !

**Comment by justaugustus** [comment]
Continued in https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/274.
/close
