### ISSUE TITLE
need to bump bazel build image in cloudbuild.yaml

### ISSUE THREAD

**Issue by listx** [kubernetes-sigs/k8s-container-image-promoter#271]
#### What happened:

Push to staging of master branch (at 2a7df3b) is failing (see https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/cip-postsubmit-push-to-staging/1318451425813991424).

#### What you expected to happen:

This should succeed. Essentially the k8s job runs `cloudbuid.yaml` in this repo to do the push to staging, but it failed today (Oct 20). I suspect maybe the Bazel updates had something to do with it. The push job itself is here: https://prow.k8s.io/?job=cip-postsubmit-push-to-staging

Logs are here in a gist in case it is not visible to those who are not in the artifact admins group: https://gist.github.com/listx/a69301c9c3b98cc4eca8a04f0946f0f3

#### How to reproduce it (as minimally and precisely as possible):

I assume any further merges to master will result in a similar failure.

#### Anything else we need to know?:

Looking at the logs, it looks like we just need to update the bazel image in cloudbuild.yaml. The key error message is:

```
Current Bazel version is 0.29.1, expected at least 1.2.0
```

I didn't expect to see the root cause when I first started filling out this bug template's details... but now that I know what is the cause, I guess I can fix it. Unless someone else would like to do the honors...

Anyone? :)

**Comment by justaugustus** [comment]
On it!
/assign

**Comment by justaugustus** [comment]
Fix is up here: https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/272
