### ISSUE TITLE
Image us.gcr.io/k8s-artifacts-prod/artifact-promoter/cip does not contain dashboard binary

### ISSUE THREAD

**Issue by cpanato** [kubernetes-sigs/k8s-container-image-promoter#274]
#### What happened:
We have the job https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/wg-k8s-infra/trusted/wg-k8s-infra-trusted.yaml#L25-L47 that runs the vulnerabilities and export a dashboard.

To run that it needs the dashboard binary that is available here: https://github.com/kubernetes-sigs/k8s-container-image-promoter/tree/master/dashboard

But this is missing when building the image `us.gcr.io/k8s-artifacts-prod/artifact-promoter/cip` and the job is failing because this binary is missing: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-k8sio-vuln-dashboard-update/1319508946259546112

I'm trying to see what is missing but I'm not an expert on bazel :/

/cc @justaugustus @listx 
/kind bug

**Comment by listx** [comment]
This probably needs to be revisited (or be made a part of) #266.

**Comment by justaugustus** [comment]
I believe the root of this is that the vulnerability dashboard binary was not actually in the `cip` image (nor do I think it should be).

So I'm have done / am doing a few things:
- [x] migrate the vulnerability dashboard (`vulndash`) to k/release: https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/276
- [x] fixup image building for vulndash: https://github.com/kubernetes/release/pull/1662
- [ ] update image locations, job refs in k/test-infra: https://github.com/kubernetes/test-infra/pull/19725

**Comment by justaugustus** [comment]
Closing in favor of https://github.com/kubernetes/release/issues/1665.
/close
