### ISSUE TITLE
Failed to install on Mac

### ISSUE THREAD

**Issue by johngmyers** [kubernetes-sigs/k8s-container-image-promoter#289]
#### What happened:

```
$ make install
bazel run //:install-cip -c opt -- /Users/jgmyers/go/bin
INFO: Analyzed target //:install-cip (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:install-cip up-to-date:
  bazel-bin/_install-cip_gen.sh
  bazel-bin/install-cip
INFO: Elapsed time: 0.499s, Critical Path: 0.11s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
install: illegal option -- -
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
make: *** [install] Error 64
```

#### What you expected to happen:

To get a working k8s-container-image-promoter binary.

#### How to reproduce it (as minimally and precisely as possible):

```
git clone https://github.com/kubernetes-sigs/k8s-container-image-promoter.git
cd k8s-container-image-promoter
make install
```

#### Environment:

- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): Mac OS 10.15.7
- Kernel (e.g. `uname -a`): Darwin iMac.localdomain 19.6.0 Darwin Kernel Version 19.6.0: Mon Apr 12 20:57:45 PDT 2021; root:xnu-6153.141.28.1~1/RELEASE_X86_64 x86_64
- Others:
bazelisk 1.9.0

**Comment by bkk-bcd** [comment]
I have a different OS and arch, so I can't verify this directly, but in my experience its not uncommon to run into incompatibilities between BSD and GNU Linux commands. I would suggest trying to install coreutils (Note: this could break other scripts you use):

```
$ brew install coreutils
```

**Comment by talbright** [comment]
I have a different OS and arch, so I can't verify this directly, but in my experience its not uncommon to run into incompatibilities between BSD and GNU Linux commands. I would suggest trying to install coreutils (Note: this could break other scripts you use):

```
$ brew install coreutils
```

**Comment by justaugustus** [comment]
Thanks for the report, @johngmyers.
Will take a look at the bazel config next week.

**Comment by listx** [comment]
FWIW there is work going to to remove Bazel in the coming weeks by @tylerferrara. See https://docs.google.com/document/d/1tQTb8dqKQtsL1a5jmCDbRg2MEDMkAnT07vrrxyZxLfk/edit?usp=sharing

**Comment by tylerferrara** [comment]
@johngmyers could you re-try pulling the latest from master?
We have now removed Bazel altogether, which may resolve your issue.

**Comment by tylerferrara** [comment]
I can confirm that CIP builds correctly on the M1 MacBook Air.

**Comment by justaugustus** [comment]
With bazel removed from the repo, this should no longer be an issue.
Please feel free to reopen if installation is still failing.

/close
