### ISSUE TITLE
Remove bazel from repo

### ISSUE THREAD

**Issue by justaugustus** [kubernetes-sigs/k8s-container-image-promoter#300]
- [x] Update to latest / roughly parity with k/k: https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/264
- [ ] ~Swap to k/repo-infra~
- [ ] Non-bazel bash/go testing
  - [x] unit tests: https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/291
  - [ ] (@tylerferrara) e2e tests: https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/304
- [ ] Non-bazel container + artifact generation
- [ ] Swap presubmits to non-bazel
- [ ] Remove bazel

/sig release
/area release-eng

/assign @tylerferrara @justaugustus
cc: @listx @kubernetes-sigs/release-engineering

**Comment by justaugustus** [comment]
Design doc from @tylerferrara: https://docs.google.com/document/d/1tQTb8dqKQtsL1a5jmCDbRg2MEDMkAnT07vrrxyZxLfk/edit?usp=sharing

cc: @kubernetes-sigs/release-engineering

**Comment by tylerferrara** [comment]
Removing Bazel from e2e tests will take several PRs. To organize this, I created a sub-issue outlining each step.
CIP e2e tests: #304

**Comment by tylerferrara** [comment]
- [x] e2e tests and completed

#323 is looking to tackle `Non-bazel container + artifact generation`

**Comment by tylerferrara** [comment]
@justaugustus Bazel is now deprecated in CIP.
Suggest closing.
