### ISSUE TITLE
Add archive verification to pull-cip-verify pre-submit test

### ISSUE THREAD

**Issue by tylerferrara** [kubernetes-sigs/k8s-container-image-promoter#326]
#### What would you like to be added:
The existing `verify-archives` target should be added to pre-submits by simply being added to the `verify` target. This would explicitly guard the archives for each PR. However, the Prow job's base image that runs current verification scripts `pull-cip-verify` does not have docker installed.
```
docker run gcr.io/k8s-staging-releng/releng-ci:latest-go1.15 whereis docker 
docker:
```
Therefore, in order to run the verification, a new image must be used, allowing docker-in-docker support to be enabled.
#### Why is this needed:
Although current golden-image archives are guarded by test manifests, if a programmer changes them, it will not break the `verify` make target. Since we already have the `verify-archives.sh` script, adding it to pre-submits adds another layer of security to the modification of golden-archives, further improving stability.

**Comment by tylerferrara** [comment]
This may not be a priority of CIP in the near future, but it's worth considering.
cc: @listx @amwat @justaugustus

**Comment by listx** [comment]
What if we used the kubekins-e2e image? It has docker.

https://github.com/kubernetes/test-infra/tree/master/images/kubekins-e2e

**Comment by amwat** [comment]
+1 kubekins-e2e should have docker and also support for docker in docker.

**Comment by tylerferrara** [comment]
Completed, closing.
