### ISSUE TITLE
Verify building with Docker

### ISSUE THREAD

**Issue by tylerferrara** [kubernetes-sigs/k8s-container-image-promoter#328]
#### What would you like to be added:
Sub-issue of #339 

The process of building container images should be guarded by tests. Currently, its possible to change the Dockerfile to use any base image and include any extra code. 

When building with `cip-image.sh` we can verify:

- Base images of each container
- Size constraints
- Number of image layers (this may change based on relied upon base images)
- Running processes (`docker top <container>`)

#### Why is this needed:
The make targets `image-push-cip-auditor-e2e` and `image-push` both rely on `push-cip.sh` to effectively build images correctly. Currently, if this script is modified, or broken, pre-submits will not warn of such a failure. Adding a test for the `push-cip.sh` will ensure the reliability of both make targets. Additionally, testing the contents of the images will strengthen trust of provenance in our container builds.

/assign
cc: @listx @amwat @justaugustus @kubernetes-sigs/release-engineering

**Comment by justaugustus** [comment]
Closed via https://github.com/kubernetes/test-infra/pull/22619
/close
