### ISSUE TITLE
add linter as a required presubmit check for all new PRs

### ISSUE THREAD

**Issue by listx** [kubernetes-sigs/k8s-container-image-promoter#36]
We already have the linting rules defined, so it's just a matter of adding another Prow job.

**Comment by Avni-Sharma** [comment]
Hey, where is the new prow job added?

**Comment by listx** [comment]
It would get added in https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-release/cip/container-image-promoter.yaml as another presubmit. We already have a linter script that uses golangci-lint (see https://github.com/kubernetes-sigs/k8s-container-image-promoter/blob/master/lint.sh).

Hmm upon further thought I think we don't track the golangci-lint dependency in Bazel. We should fix that first.

**Comment by listx** [comment]
I opened #39 for this. Let's do that one first.

**Comment by listx** [comment]
Fixed by https://github.com/kubernetes/test-infra/pull/13909

/close
