### ISSUE TITLE
move CI logic into separate scripts

### ISSUE THREAD

**Issue by listx** [kubernetes-sigs/k8s-container-image-promoter#5]
I.e., strip out steps from cloudbuild.yaml and elsewhere into standalone scripts.

**Comment by amy** [comment]
@listx I have time to tackle this. Can you assign this issue to me.
Is there anything special other than these instructions that I need to follow in order to sanity test the moved logic: https://cloud.google.com/cloud-build/docs/create-custom-build-steps

**Comment by dims** [comment]
@amy can you please request membership to the kubernetes-sigs org?

**Comment by amy** [comment]
@dims Ah nevermind. I can't be assigned issues yet.

**Comment by dims** [comment]
@amy please consider yourself assigned :)

**Comment by listx** [comment]
@amy  Whatever logic in cloudbuild.yaml should be stripped out into separate shell scripts, and then moved into a new Prow job as per #6.

**Comment by listx** [comment]
This is now tied to #8.

**Comment by listx** [comment]
This is fixed. In a twist of irony, there isn't much shell code in the codebase any more, because we delegate so much to bazel. So, there isn't much "CI logic to put into separate shell scripts" to begin with.

/close
