### ISSUE TITLE
Use klog everywhere for logging

### ISSUE THREAD

**Issue by listx** [kubernetes-sigs/k8s-container-image-promoter#54]
Delete the (basic) homegrown stuff in https://github.com/kubernetes-sigs/k8s-container-image-promoter/blob/5fb3b400034911b811880310b2b45257874df6a6/lib/dockerregistry/inventory.go#L72

**Comment by Jukie** [comment]
Just so I understand the context, is the intent to get rid of all these lines and replace any existing references with klog? 
https://github.com/kubernetes-sigs/k8s-container-image-promoter/blob/master/lib/dockerregistry/inventory.go#L72-#L124

**Comment by listx** [comment]
Yes exactly. Those lines were added as a temporary measure but now that we are using klog as a dependency, we use use klog instead.

**Comment by listx** [comment]
There is #67 for this now.
