### ISSUE TITLE
use Prow for CI

### ISSUE THREAD

**Issue by listx** [kubernetes-sigs/k8s-container-image-promoter#6]
#1 adds support for using GCB, but Prow is much more powerful.

Then we can enable /lgtm commands and such. This also requires setting up an OWNERS file. See https://github.com/kubernetes/test-infra/tree/master/prow/plugins/approve/approvers

**Comment by amy** [comment]
Gonna probably submit this in 5 separate PRs for each separate docker image that correlates with the old cloud-build yaml (setup, lint, test, build-image, push-image)

**Comment by amy** [comment]
@listx A question I have about this issue is, when you say use Prow for ci, was there something more than migrating the `cloudbuild.yaml` file?

**Comment by listx** [comment]
> @listx A question I have about this issue is, when you say use Prow for ci, was there something more than migrating the `cloudbuild.yaml` file?

Yes, the e2e tests from #8 will get added in at some point, so that we test how the promoter actually behaves with new changes.

**Comment by listx** [comment]
Fixed with

https://github.com/kubernetes/test-infra/pull/13909
https://github.com/kubernetes/test-infra/pull/14000

/close
