### ISSUE TITLE
make the promoter act recursively for all manifests found under a directory

### ISSUE THREAD

**Issue by listx** [kubernetes-sigs/k8s-container-image-promoter#64]
Instead of telling the promoter "here is the manifest, here is the SA, please do the promotion" (as we do with util/multirun.sh today), we should be able to say "here is a directory full of manifests and SA configuration info --- please perform promotions for all manifests found there". This is purely a convenience function, but very real and necessary.

Practically speaking, once this feature is implemented we could just add new staging repositories in github.com/kubernetes/k8s.io/k8s.gcr.io with a PR and that would be it --- the existing Prow job would just pick it up automatically (no need to update the Prow job to be invoked with the new staging repo manifest). It's a big win for convenience.

**Comment by listx** [comment]
I think this would be simpler to implement if we made it so that all manifests within a directory all share the same SA creds. This is how it would look like in practice anyway, where we would give `k8s-infra-gcr-promoter@k8s-cip-test-prod.iam.gserviceaccount.com` the rights to read from all staging GCRs (that is, we already want to limit the number of write-access SAs to the prod GCR, so we would naturally just use 1 for it).

There are many possibilities, but one springs to mind: we will only read child manifests' src registry information. Then for each image that has to get promoted, we do a set difference with the dest registries and the src registry that is supposed to have that image. This means that SyncContext.SrcRegistry will no longer be a single registry, but a list (or map --- map would make it easier to do a check for membership without explicit looping). The rest of the business logic should more or less be the same.

There are basically 2 parts to this: (1) implement recursive filesystem tree-walk logic to first read in the set of manifests; (2) implement multi-src repository set difference/promotion logic.

**Comment by listx** [comment]
Putting down some more thoughts here to record the discussion in the wg-k8s-infra meeting today: we can greatly simplify the problem if we ignore multi-manifest consistency and frame this task around just making the logic in `util/multirun.sh` smarter. That is, we can make that logic make the promoter run for *any* manifest (perhaps matching a certain path prefix) that changed across git commits. Today we just limit ourselves to those listed explicitly as an argument to `multirun.sh`, but we could extend that script to make it run dynamically for those manifests found under a directory.

Ideally we would port the logic in multirun.sh into Go, so that we have less shell code.

**Comment by listx** [comment]
Another note: we still have to make the promoter read in *all* manifests recursively for those sanity runs that ensure that the intent is realized for *all* images. The git delta stuff doesn't make sense for this use case.

**Comment by listx** [comment]
I have begun implementing this. Along the way, I have come across an idea for simplifying how we determine what to promote. Expect a PR this week for this @justinsb

**Comment by spiffxp** [comment]
/close
this is done via above PRs

**Comment by spiffxp** [comment]
/reopen
sounds like it's coded but not deployed, let's close this once the new functionality is in a version of the code that's currently running

**Comment by listx** [comment]
Fixed with https://github.com/kubernetes/test-infra/pull/14012

/close
