### ISSUE TITLE
Create test Google service account

### ISSUE THREAD

**Issue by amy** [kubernetes-sigs/k8s-container-image-promoter#65]
From: https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/62

```
@listx 
We should give k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
"Storage Admin" and "Storage Object Admin" perms for the test-only GCRs:
- gcr.io/k8s-staging-cip-test
- gcr.io/k8s-cip-test-prod
```

**Comment by amy** [comment]
Also related: https://github.com/kubernetes/k8s.io/blob/master/infra/gcp/lib.sh
@dims suggests we should update this script: https://github.com/kubernetes/k8s.io/blob/master/infra/gcp/lib.sh

**Comment by listx** [comment]
And for the record, we should choose a *new* test-only SA, and not reuse `k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com` for this.

**Comment by amy** [comment]
In progress: Working on updating the lib.sh script (and learning some bash)

**Comment by thockin** [comment]
Send me the PR when ready :)

**Comment by amy** [comment]
/close 

From clarification in https://github.com/kubernetes/k8s.io/pull/302
These service accounts exist.
