### ISSUE TITLE
Protecting promotion credentials

### ISSUE THREAD

**Issue by amy** [kubernetes-sigs/k8s-container-image-promoter#69]
Broad issue to track how we're going to make sure the promotion credentials to the production registries will be secured against bad actors.

**Comment by amy** [comment]
tagging @cblecker

**Comment by cblecker** [comment]
Prow has concepts like a "trusted cluster" that we use for handling highly privileged credentials (like github owner creds). The promotion job should be set to run on our trusted cluster.

cc: @BenTheElder @fejta

**Comment by BenTheElder** [comment]
So my $.02

If we run every publish / build job in "the" trusted cluster it may not be so trusted anymore and a random SIG project may have something sneak into their built that say, steals @k8s-ci-robot's credentials...

Much as we might not want _more_ clusters, I think build type stuff should generally not be in the same cluster as Prow's credentials, except maybe building Prow itself.

**Comment by BenTheElder** [comment]
Also note that today the trusted cluster == where prow's services run. Even if we decide that's not a problem trust wise, piling on more builds is going to require at least expanding the capacity.

---

IMHO we should also put a default request / resource limit in the trusted cluster(s) to avoid problems before we add much more to it, since there's less workloads it will be easier. That cluster is more sensitive to overloading the nodes (since we're disrupting E.G. the infra workloads, instead of just a presubmit).

**Comment by amy** [comment]
Also tagging @thockin

**Comment by cblecker** [comment]
Building the image is different than the promotion job. The promotion job should be just one job for all the staging repos if I understand correctly (consumes one config of the hashes to copy up)

**Comment by BenTheElder** [comment]
👍

That should absolutely run there :-)
Please consider my other comments irrelevant off topic.

**Comment by listx** [comment]
I believe this might just go away once Workload Identity gets used by the Prow jobs (sometime in H12020).

**Comment by BenTheElder** [comment]
workload identity happened today. that does not mean all things actually
use it though (in fact most things do not)

**Comment by bartsmykla** [comment]
@amy @listx what is the status of this issue currently?

**Comment by fejta** [comment]
https://github.com/kubernetes/test-infra/pull/16463 is waiting for some review and is part of what is needed

**Comment by bartsmykla** [comment]
Thank you @fejta for update!

@listx I know you have a lot on your plate currently but would you be able to do some quick review for @fejta?
