### ISSUE TITLE
Create e2e test for use in CI (to actually promote/demote images in Docker Registries)

### ISSUE THREAD

**Issue by listx** [kubernetes-sigs/k8s-container-image-promoter#8]
The idea is, we can create a test (as a Prow Job) to populate 2 test GCRs --- a fake "staging" and a fake "production" GCR. Then we would rotate through 1 or more different promoter manifests, with various flags passed to the promoter, and expect the target registry to look a certain way after the promoter finishes.

We could do the above multiple times in the test. This would be great to test things like garbage collection and whatnot, and other more advanced features of the promoter that might be implemented in the future (e.g., multi-stage promotions, replication, etc.).

The basic ingredients are:
- Have some logic to create real Docker images deterministically (bazel already does this...)
- Populate a staging GCR with these images
- Run a just-compiled promoter (as a presubmit) and run it against a battery of various promoter manifest.yamls.

All of the above could run in a Prow step. It would simply fetch an image with gcloud + bazel, then compile the promoter and then run it.

The integration test would enable developers (who might not have a Docker Registry to play with or have GCP accounts set up) to make changes (such as refactorings) without fear of modifying the behavior of the promoter.

The original idea of the various components of how an integration test might work is documented [here](https://docs.google.com/document/d/1WGFt5ck_XGf71PO4c87UMPVU_4Q7AV-7tRV4Z6wmZL4/edit?usp=sharing).

**Comment by listx** [comment]
For the actual images used during testing, another alternative is to use a set of known images and to just check these in as long as they are reasonably small. Ultimately, we need to test for:

- plain images
- manifest lists (aka "fat manifests") that reference multiple images
- windows images
- images with foreign layers

For the more exotic images like windows images and foreign layers (ones we might have trouble generating deterministically), the options are:
- find (very small!) versions of these and check them into our source tree directly
- find small images and copy them into a safe GCR location that we own

**Comment by listx** [comment]
I will create a short design doc for this before starting work on this.

**Comment by listx** [comment]
The design doc is here: https://docs.google.com/document/d/1PgLI7OCEd09qLLz9yGmY2KK0uxhROc9GGC-PkwgnKN4/edit?usp=sharing

**Comment by listx** [comment]
I got some code written over KubeCon for this. I have a crude script that can delete all images from the  test-only repos, and also repopulate it with deterministic docker images created with bazel, plus a manifest list.

I will continue to work on this in my own spare time, but feel free to ping me to ask for updates either here or on Slack (#wg-k8s-infra).

**Comment by listx** [comment]
@justinsb It's not finished yet, but here is some WIP code for this effort: https://github.com/listx/k8s-container-image-promoter/tree/e2e

**Comment by amy** [comment]
@listx Trying to see where I can help out here. Any chance you're able to give an overview of what you have done in that WIP.

**Comment by listx** [comment]
Update on this effort: @amy will help set up the e2e jobs in the untrusted prow cluster. You can also see updates in the design doc https://docs.google.com/document/d/1PgLI7OCEd09qLLz9yGmY2KK0uxhROc9GGC-PkwgnKN4/edit?usp=sharing

**Comment by listx** [comment]
Fixed with https://github.com/kubernetes/test-infra/pull/13909

/close
