### ISSUE TITLE
run s/registry/repository find-and-replace across the codebase and README

### ISSUE THREAD

**Issue by listx** [kubernetes-sigs/k8s-container-image-promoter#90]
In practice, we only really deal with repositories, not registries (registries are unique top-level endpoints --- so in the case of GCR, the regional registries). The constant back/and/forth between these two terms in the codebase is rather confusing.

**Comment by bartsmykla** [comment]
/remove-lifecycle rotten

Hi @listx!
Is this still a thing?

**Comment by listx** [comment]
Yes --- some low-hanging fruit for people wanting to contribute.

**Comment by bartsmykla** [comment]
Great! I will have it in mind :-)
